### ISSUE TITLE
JEST - Cannot find module 'single-spa-react/parcel' from 'root.component.js

### ISSUE THREAD

**Issue by hugocalheira** [single-spa/single-spa-react#103]
My application is running well and no errors are ocurring.

But when I run the test suite, I got this:
![image](https://user-images.githubusercontent.com/6580989/107583210-5bf83300-6bd9-11eb-92e4-f106e1245dc9.png)

I tried to import directly from `single-spa-react/lib/esm/parcel` but with no success... :/

```
"devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/plugin-transform-runtime": "^7.12.1",
    "@babel/preset-env": "^7.12.7",
    "@babel/preset-react": "^7.12.7",
    "@babel/runtime": "^7.12.5",
    "@testing-library/jest-dom": "^5.11.6",
    "@testing-library/react": "^11.2.2",
    "@types/jest": "^26.0.16",
    "@types/systemjs": "^6.1.0",
    "babel-eslint": "^11.0.0-beta.2",
    "babel-jest": "^26.6.3",
    "concurrently": "^5.3.0",
    "cross-env": "^7.0.3",
    "eslint": "^7.15.0",
    "eslint-config-prettier": "^7.0.0",
    "eslint-config-react-important-stuff": "^3.0.0",
    "eslint-plugin-prettier": "^3.2.0",
    "husky": "^4.3.5",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^26.6.3",
    "jest-cli": "^26.6.3",
    "prettier": "^2.2.1",
    "pretty-quick": "^3.1.0",
    "single-spa-react": "^3.2.0",
    "webpack": "^5.8.0",
    "webpack-cli": "^4.2.0",
    "webpack-config-single-spa-react": "^2.0.0-beta.1",
    "webpack-dev-server": "^4.0.0-beta.0",
    "webpack-merge": "^5.4.0"
  }
```

**Comment by joeldenning** [comment]
Please upgrade to single-spa-react@4, which fixed all the types. See https://github.com/single-spa/single-spa-react/releases/tag/v4.0.0. [This test](https://github.com/single-spa/single-spa-react/blob/602f22d7b2439eb4584348719526ef7bba82464a/src/single-spa-react.test-d.ts#L5) shows that parcel imports are working, and I also confirmed it locally in a sample project.

**Comment by gjhommersom** [comment]
We have been running into this issue as well when updating from `2.14.0` to `4.1.1`. We are able to run the tests when we change the import to `single-spa-react/lib/umd/parcel` but then the production build fails.

It is also possible to reproduce this problem using a brand new project created using `create-single-spa@2.2.2`. 
Options:
* react
* app/parcel
* yarn
* typescript

After that has run all we have to change is the root component and run `yarn test`. 
```
import React from "react";
import Parcel from 'single-spa-react/parcel'

export default function Root(props) {
  return <section><Parcel config={()=>{return System.import('')}}/></section>;
}
```

P.S. When running create-single-spa we get this message `A patch update of create-single-spa is available: 2.3.1 → 2.2.2` but a `2.3.x` version is not available for download.

**Comment by gjhommersom** [comment]
Using `2.2.3` of `create-single-spa` fixes the warning but the issue remains.

**Comment by joeldenning** [comment]
It's possible jest's module resolution algorithm does not yet support [nodejs package entry points](https://nodejs.org/dist/latest-v16.x/docs/api/packages.html#packages_package_entry_points), which are required for `single-spa-react/parcel` to correctly resolve to the `node_modules/single-spa-react/lib/cjs/parcel.cjs` file that should be used, as specified in [this code](https://github.com/single-spa/single-spa-react/blob/68308bf648a6a46fd7e56f292b5a8331eb992e21/package.json#L15).

See https://github.com/facebook/jest/issues/9771 where this issue with jest is being discussed.

To workaround, you can use [moduleNameMapper](https://jestjs.io/docs/configuration#modulenamemapper-objectstring-string--arraystring)

```
// jest.config.js
module.exports = {
  moduleNameMapper: {
    "single-spa-react/parcel": "single-spa-react/lib/cjs/parcel.cjs"
  }
}
```

That config will get you close, but might not work exactly. If it doesn't, try using `node_modules/single-spa-react/lib/cjs/parcel.cjs` as the file path in the moduleNameMapper.

**Comment by joeldenning** [comment]
If you get it working, a contribution adding this to create-single-spa would be welcome.

**Comment by gjhommersom** [comment]
I will give it a shot.
