### ISSUE TITLE
Cannot find module '@org/project' from 'App.js'

### ISSUE THREAD

**Issue by rohanshukla** [single-spa/single-spa-react#107]
Hi, @joeldenning 
I am exporting component and function from another application and in-browser utility module, 
everything works fine in development but while testing the react component using jest facing the issue of
`Cannot find module '@org/project' from 'App.js'`

how can i resolve this issue

![Screenshot from 2021-03-20 15-24-37](https://user-images.githubusercontent.com/34018777/111866174-9780dc80-8991-11eb-814f-144b213daf95.png)

**Comment by PieterBoeren** [comment]
If I remember correctly (can't test it now), I had the same issue, I was able to solve it with a "transformIgnorePatterns" in the jest config like:

```transformIgnorePatterns: [`/node_modules/(?!@whateveryourorgnameis)`],```

**Comment by frehner** [comment]
See https://github.com/single-spa/single-spa.js.org/issues/389 and also https://jestjs.io/docs/manual-mocks 

👍
