### ISSUE TITLE
Issue with IE 11

### ISSUE THREAD

**Issue by HarithaKR** [single-spa/single-spa-react#110]
Hi. https://github.com/single-spa/single-spa-react/issues/109

In the above issue, my issue was not resolved with that response. In the  example you attached, there is no importing of another application to this. Can you show an example of importing a react application to this application? Both react and that works in IE11?

**Comment by frehner** [comment]
Please comment in that issue, and do not open a new issue. Thanks.

**Comment by HarithaKR** [comment]
I have commented there.  As its closed, I had to open a new one.
