### ISSUE TITLE
Prepare for React 18's `createRoot`

### ISSUE THREAD

**Issue by frehner** [single-spa/single-spa-react#112]
Based on the discussion here: https://github.com/reactwg/react-18/discussions/5 , specifically the `What about the render callback?` section, I _think_ we'll need to update the `whenFinished` call here https://github.com/single-spa/single-spa-react/blob/1237c68185f8178378c19c22927d46de98e15983/src/single-spa-react.js#L248-L251

According to that ReactWG discussion

>In the New Root API, we’ve removed this callback.

So we'll need to follow their example and use a ref to the root app to know when it's been rendered. 

If that makes sense.

**Comment by joeldenning** [comment]
Thanks for raising this. Best approach might be to do something similar to what we did for error boundaries, where we modify the elementToRender to be a different root component that is one within single-spa-react itself? See code below:

https://github.com/single-spa/single-spa-react/blob/1237c68185f8178378c19c22927d46de98e15983/src/single-spa-react.js#L279-L284

I have some time right now and will look into it.

**Comment by joeldenning** [comment]
Added support for React 18 at #114
