### ISSUE TITLE
PR #114 broke Parcel update lifecycle

### ISSUE THREAD

**Issue by Grisu118** [single-spa/single-spa-react#117]
It seems that the pr #114 to support react 18 destroyed the update lifecycle of parcels. 

See following example: https://codesandbox.io/s/eager-leavitt-5opmv

You removed the whenFinished as parameter here: https://github.com/single-spa/single-spa-react/commit/b555cd6e8a4766bc9cca0556bf0b00464a9f8480#diff-c5eaff085b5e6099025d960035472f3294bb99ba188311b924d7987a6f8f919eR251

But it is still passed in the update lifecycle method and expected to be called. 

> single-spa minified message #31: Lifecycle function update for parcel parcel-0 lifecycle did not resolve or reject for 3000 ms. See https://single-spa.js.org/error/?code=31&arg=update&arg=parcel&arg=parcel-0&arg=3000

**Comment by joeldenning** [comment]
I've confirmed that this is a bug and have begun work on fixing it. Will submit a pull request in the next few days or so

**Comment by joeldenning** [comment]
Fix released in https://github.com/single-spa/single-spa-react/releases/tag/v4.2.1
