### ISSUE TITLE
Lastest Version Can't Update Single-Spa-React Component Props

### ISSUE THREAD

**Issue by dkypooh** [single-spa/single-spa-react#121]
![image](https://user-images.githubusercontent.com/2450624/126886937-657005a7-798f-4969-a7a7-10a564a564e2.png)

Hi, Author

Background：
1. When User Update Parcel Custom Props，HOC Component Entry componentDidUpdate lifecycle， 
2. Using Promise Queue，To Update Single-Spa-React Componont where Provider Product。 

Problem：
1. When Do Update Function，No Promise Return To Finish，Leader To Next Promise(Update Operate) Can't Work

Solution:
1. May be Use whenFinished Function When Render Callback

**Comment by joeldenning** [comment]
See https://github.com/single-spa/single-spa-react/issues/117 and https://github.com/single-spa/single-spa-react/issues/112 for the explanation of why the code changed.

What version of React are you using? Could you please provide a demonstration of the issue (Github repo with instructions to show problem)

**Comment by rudavko** [comment]
Hey @joeldenning I've stumbled upon same issue. Here is a codesandbox with the issue reproduced:
https://codesandbox.io/s/dank-waterfall-xowkr

I've used your sandbox (https://codesandbox.io/s/dazzling-jackson-lmudo?file=/index.html), and just updated single-spa-react to 4.3.1 version, which broke the counter.

Hope this helps. Feel free to reach out to me, would be happy to help :)

**Comment by joeldenning** [comment]
Thanks for providing the demonstration and being willing to contribute a fix. I debugged it and found the issue and had some time to fix it in #126. Feel free to review the pull request @rudavko. The core team will also be reviewing it.

**Comment by joeldenning** [comment]
Fix released in https://github.com/single-spa/single-spa-react/releases/tag/v4.4.0. Please let me know if that version works for you or if you still have any issues with React 16 usage.
