### ISSUE TITLE
Set default custom props when mode is standalone

### ISSUE THREAD

**Issue by thuram** [single-spa/single-spa-react#123]
Hello, im using `single-spa-react` and this MFE received some props when is called: 

```js
export default function Root({
  access_token,
  oam_cookie,
  locale,
  cart_id
}: AppProps) {}
```

I would like know is possible set this props with default value when project is running in `standalone mode`. The script to run in standalone mode is: `"start": "webpack serve -- --port=9001",`

**Comment by joeldenning** [comment]
I'm open to this being added. The change would need to be made in standalone-single-spa-plugin. See https://github.com/single-spa/standalone-single-spa-webpack-plugin/blob/d6a6742d5699f2f02b0a59003eb749752f3f45cb/lib/standalone-single-spa.js#L248 where the `registerApplication` occurs in standalone mode. Do you have interest in submitting a PR that allows passing in customProps?

**Comment by joeldenning** [comment]
Implemented in https://github.com/single-spa/standalone-single-spa-webpack-plugin/pull/16

**Comment by joeldenning** [comment]
Released in https://github.com/single-spa/standalone-single-spa-webpack-plugin/releases/tag/v2.1.0
