### ISSUE TITLE
Adding styles to app

### ISSUE THREAD

**Issue by FBurner** [single-spa/single-spa-react#124]
Hi,

it seems you cant apply flexbox to the apps?

At least i did not find any attributes for that.

 "single-spa": "^5.9.0",

**Comment by joeldenning** [comment]
Flexbox is built into the browser - single-spa cannot change or remove that functionality. You can use flexbox.

**Comment by FBurner** [comment]
Maybe it was not clearly formulated from my side. I dont see how i can add classes or styles to the root of the applications.

**Comment by joeldenning** [comment]
What do you mean by "root of the applications"? Are you referring to `<div id="single-spa-application:app-name"></div>`? If so, you can style it with the following css:

```css
#single-spa-application\:app-name {
  display: flex;
}
```
