### ISSUE TITLE
TSC Build Errors 

### ISSUE THREAD

**Issue by tvblomberg** [single-spa/single-spa-react#129]
Hi single-spa Team,

I want to start out by saying how impressed I am with single-spa.

I just started using it and is exactly what I am looking for.

I used the create-single-spa cli to generate a root config application.

While running yarn build I get the following typescript errors:

`invincent@pop-os:~/Dev/Work/Hackathons/FE/root$ yarn run build
yarn run v1.22.5
warning package.json: No license field
$ concurrently yarn:build:*
warning package.json: No license field
warning package.json: No license field
$ webpack --mode=production
$ tsc
[build:webpack] asset bifrost-root-config.js 18.6 KiB [compared for emit] [minimized] (name: main) 1 related asset
[build:webpack] asset index.html 1.95 KiB [compared for emit]
[build:webpack] runtime modules 344 bytes 3 modules
[build:webpack] orphan modules 16.8 KiB [orphan] 1 module
[build:webpack] built modules 21 KiB [built]
[build:webpack]   modules by path ./node_modules/systemjs-webpack-interop/ 3.27 KiB
[build:webpack]     ./node_modules/systemjs-webpack-interop/auto-public-path/1.js 89 bytes [built] [code generated]
[build:webpack]     ./node_modules/systemjs-webpack-interop/auto-public-path/auto-public-path.js 846 bytes [built] [code generated]
[build:webpack]     ./node_modules/systemjs-webpack-interop/public-path.js 2.36 KiB [built] [code generated]
[build:webpack]   ./src/bifrost-root-config.ts + 1 modules 17.7 KiB [built] [code generated]
[build:webpack]   external "single-spa" 42 bytes [built] [code generated]
[build:webpack] webpack 5.58.1 compiled successfully in 2314 ms
[build:webpack] yarn run build:webpack exited with code 0
[build:types] node_modules/single-spa-layout/dist/types/browser/constructApplications.d.ts(36,5): error TS1170: A computed property name in a type literal must refer to an expression whose type is a literal type or a 'unique symbol' type.
[build:types] node_modules/single-spa-layout/dist/types/browser/constructApplications.d.ts(36,5): error TS2464: A computed property name must be of type 'string', 'number', 'symbol', or 'any'.
[build:types] node_modules/single-spa-layout/dist/types/isomorphic/constructRoutes.d.ts(74,81): error TS2694: Namespace '"/home/invincent/Dev/Work/Hackathons/FE/root/node_modules/@types/parse5/index"' has no exported member 'DefaultTreeDocument'.
[build:types] node_modules/single-spa-layout/node_modules/single-spa/typings/single-spa.d.ts(1,1): error TS6200: Definitions of the following identifiers conflict with those in another file: CustomPropsFn, AppProps, ParcelConfig, ParcelProps, ParcelConfigObject, Parcel, LifeCycleFn, LifeCycles, StartOpts, Application, ActivityFn, Activity, RegisterApplicationConfig, SingleSpaCustomEventDetail, NOT_LOADED, LOADING_SOURCE_CODE, NOT_BOOTSTRAPPED, BOOTSTRAPPING, NOT_MOUNTED, MOUNTING, MOUNTED, UPDATING, UNMOUNTING, UNLOADING, SKIP_BECAUSE_BROKEN, LOAD_ERROR, AppError
[build:types] node_modules/single-spa-layout/node_modules/single-spa/typings/single-spa.d.ts(3,5): error TS2374: Duplicate index signature for type 'string'.
[build:types] node_modules/single-spa-layout/node_modules/single-spa/typings/single-spa.d.ts(4,5): error TS2374: Duplicate index signature for type 'number'.
[build:types] node_modules/single-spa-layout/node_modules/single-spa/typings/single-spa.d.ts(98,5): error TS2374: Duplicate index signature for type 'string'.
[build:types] node_modules/single-spa/typings/single-spa.d.ts(1,1): error TS6200: Definitions of the following identifiers conflict with those in another file: CustomPropsFn, AppProps, ParcelConfig, ParcelProps, ParcelConfigObject, Parcel, LifeCycleFn, LifeCycles, StartOpts, Application, ActivityFn, Activity, RegisterApplicationConfig, SingleSpaCustomEventDetail, NOT_LOADED, LOADING_SOURCE_CODE, NOT_BOOTSTRAPPED, BOOTSTRAPPING, NOT_MOUNTED, MOUNTING, MOUNTED, UPDATING, UNMOUNTING, UNLOADING, SKIP_BECAUSE_BROKEN, LOAD_ERROR, AppError
[build:types] node_modules/single-spa/typings/single-spa.d.ts(3,5): error TS2374: Duplicate index signature for type 'string'.
[build:types] node_modules/single-spa/typings/single-spa.d.ts(4,5): error TS2374: Duplicate index signature for type 'number'.
[build:types] node_modules/single-spa/typings/single-spa.d.ts(98,5): error TS2374: Duplicate index signature for type 'string'.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[build:types] yarn run build:types exited with code 2
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

**Comment by joeldenning** [comment]
The fix for this is released in create-single-spa@4.1.2. See https://github.com/single-spa/create-single-spa/blob/main/packages/generator-single-spa/CHANGELOG.md#412
