### ISSUE TITLE
Loading single-spa react assets

### ISSUE THREAD

**Issue by Yurii-Yanovitsky** [single-spa/single-spa-react#130]
How would you implement loading assets with single-spa react app? Is it still using the webpack public path as it was discribed here https://github.com/single-spa/single-spa-angular/issues/59. How to do it in more elegant way?

**Comment by Yurii-Yanovitsky** [comment]
Thanks)

**Comment by saif1756** [comment]
@Yurii-Yanovitsky : did that work am finding it difficut to access the assets in my angular app.
