### ISSUE TITLE
Can't resolve 'single-spa-react/parcel'

### ISSUE THREAD

**Issue by haixiangyan** [single-spa/single-spa-react#132]
I follow the [docs]() to import the `Parcel` from `single-spa-react/parcel`, and it said: `Module not found: Can't resolve 'single-spa-react/parcel'`. 

I use these codes to import the `Parcel` component:

```ts
import React from 'react';
import Parcel from 'single-spa-react/parcel'

const HelloParcel: FC = () => {
  return (
    <div>
      <Parcel
        config={() => import('../../../../apps/react-app/src/Hello')}
        wrapWith="div"
      />
      Hello Parcel
    </div>
  )
}
```

![](https://user-images.githubusercontent.com/17061654/141615645-2a9abdac-173c-44be-b7c5-8b381ee13219.png)

Am I missing any other steps? I am sure I have already installed the `single-spa-react` package.

**Comment by filoxo** [comment]
What version of Webpack is your project using? That matters in how modules are resolved. See also: https://github.com/single-spa/single-spa-react/releases/tag/v3.0.0

**Comment by joeldenning** [comment]
Closing this as likely solved by the migration notes in the release notes that @filoxo linked to. Feel free to comment further or reopen if that's not the case.
