### ISSUE TITLE
How to deal with libraries that aren't exported as UMD?

### ISSUE THREAD

**Issue by Darksoulsong** [single-spa/single-spa-react#139]
I'm doing some testing with MFEs, and I've created a framework with 3 apps.  

These MFEs share some libraries, so I added them to the "externals" array in webpack.config and included them in the "importMaps" of the root config.   I'm getting an error because these libraries are not in UMD format, like Zustand for example (https://unpkg.com/browse/zustand@3.6.8/);

  There's a comment in the index.ejs file about the accepted formats (UMD, Global variable or registered via System.register). Would you provide us with an example on how this can be done, please? Of course, I could ask to the Zustand devs to add a UMD  version to the repo, but there are a couple libs with this same issue - so it makes sense to deal with it dynamically using SystemJS.  
  
  Any help would be great!

**Comment by filoxo** [comment]
If the library does not provide the right formats, someone needs to. Oftentimes this can also be found by searching for a project's "CDN version". Other possibilities are to look at repackaging the library yourself under [@esm-bundle](https://github.com/esm-bundle/) ([explainer article here](https://medium.com/@joeldenning/an-esm-bundle-for-any-npm-package-5f850db0e04d)), or check if you can find a repackaged version at [jspm](https://jspm.org/docs/api). 

Lastly, it appears [Zustand exports UMD and System versions as of version 3.6.9](https://github.com/pmndrs/zustand/releases/tag/v3.6.9).
