### ISSUE TITLE
Getting warning from ReactDOM when using React 18

### ISSUE THREAD

**Issue by JeffWeim** [single-spa/single-spa-react#142]
Hello,

When upgrading to React 18 and using single-spa-react with the following configuration:

```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import singleSpaReact from 'single-spa-react';

import Root from './root.component';

const lifecycles = singleSpaReact({
  React,
  ReactDOM,
  rootComponent: Root,
  renderType: 'createRoot',
});
```

I get the following warning in the console: `Warning: You are importing createRoot from "react-dom" which is not supported. You should instead import it from "react-dom/client".`

However, the single-spa-react api is requiring ReactDOM to be passed. Would it be better to pass the `createRoot` function here or drop the requirement of passing ReactDOM when using React 18?

**Comment by filoxo** [comment]
I unfortunately don't have time to today to setup an example project with React 18. If you can share one, that'd be a huge help. But looking at [how we're using ReactDOM within single-spa-react](https://github.com/single-spa/single-spa-react/blob/main/src/single-spa-react.js#L218), I think a possible workaround could be to import from react-dom/client, alias as ReactDOM, and pass that in.

```diff
import React from 'react';
- import ReactDOM from 'react-dom';
+ import * as ReactDOM from 'react-dom/client';
import singleSpaReact from 'single-spa-react';

import Root from './root.component';

const lifecycles = singleSpaReact({
  React,
  ReactDOM,
  rootComponent: Root,
  renderType: 'createRoot',
});
```

Or more verbosely but matches the [new import syntax here](https://github.com/reactwg/react-18/discussions/5).

```diff
import React from 'react';
- import ReactDOM from 'react-dom';
+ import * as ReactDOMClient from 'react-dom/client';
import singleSpaReact from 'single-spa-react';

import Root from './root.component';

const lifecycles = singleSpaReact({
  React,
-  ReactDOM,
+  ReactDOM: ReactDOMClient,
  rootComponent: Root,
  renderType: 'createRoot',
});
```

If that works, we can document or update the api change for React 18.

**Comment by hijiangtao** [comment]
As the newest code shows, single-spa-react has already supported React with `renderType` set to `createRoot`, but it seems ReactDOM definition still remains old? 

> TS2740: Type 'typeof import("\*\*/node_modules/@types/react-dom/client")' is missing the following properties from type 'typeof import("\*\*/node_modules/@types/react-dom/index")': findDOMNode, unmountComponentAtNode, createPortal, flushSync, and 5 more.  

I think I can run a demo to see if it this library is ready for React v18+?

**Comment by hijiangtao** [comment]
@filoxo I test it with `import ReactDOM from 'react-dom/client';`, and it shows `single-spa-react@4.6.1` supports it in single-spa's rendering, but as I said above, maybe the type of ReactDOM should be changed to support React v18+, so that I don't need to add @ts-ignore comments:

```
singleSpaReact({
      React,
      // @ts-ignore
      ReactDOM,
      renderType: 'createRoot',
      ...
    }),
```

**Comment by filoxo** [comment]
Oh right, TypeScript. Those can be updated here: https://github.com/single-spa/single-spa-react/blob/main/types/single-spa-react.d.ts#L9

**Comment by hijiangtao** [comment]
> Oh right, TypeScript. Those can be updated here: [https://github.com/single-spa/single-spa-react/blob/main/types/single-spa-react.d.ts#L9](https://github.com/single-spa/single-spa-react/blob/main/types/single-spa-react.d.ts?rgh-link-date=2022-04-15T04%3A33%3A57Z#L9)

It seems type of ReactDOM may be ambiguous from two different source, maybe it can be passed from `RootComponentProps` and not infer from `typeof`? Or simply, I searched current single-spa-react, and it only uses `createRoot` in mount lifecycle, maybe additional union type can also work?

```
export function createRoot(container: Element | DocumentFragment, options?: RootOptions): Root;
```

ps: maybe some conditions should be updated again, since v18+ already is a stable version and functions like this https://github.com/single-spa/single-spa-react/blob/main/src/single-spa-react.js#L213 may not exist anymore?

**Comment by mazenchami** [comment]
Does anyone have an update on this? I'm still getting the error shown below—FYI I'm using layout engine. If I check the network tab, I can see the `ReactVersion = 18`. I've also listed my package.json and render code:
<img width="200" alt="Screen Shot 2022-04-22 at 11 56 45 AM" src="https://user-images.githubusercontent.com/9324607/164751100-c8dda32d-996e-4e8d-85c8-01cd5724cead.png" />
```package.json:
...
"react": "^18.0.0",
"react-dom": "^18.0.0",
...
```
```
import React from "react";
import * as ReactDOMClient from "react-dom/client";
import singleSpaReact from "single-spa-react";
import Root from "./root.component";

const lifecycles = singleSpaReact({
  React,
  ReactDOM: ReactDOMClient,
  rootComponent: Root,
  renderType: 'createRoot',
  errorBoundary(err, info, props) {
    // Customize the root error boundary for your microfrontend here.
    return null;
  },
});

export const { bootstrap, mount, unmount } = lifecycles;
```

**Comment by mazenchami** [comment]
Please ignore my message above, I was able to get it to work with the above code, my issue, I didn't override the importmap to point to localhost 🤦

**Comment by JeffWeim** [comment]
@filoxo I do believe you initial comment fixes the warning. I'm wondering if the type definition file single-spa-react.d.ts should also be updated?  

```diff
import * as React from "react";
- import * as ReactDOM from "react-dom";
+ import * as ReactDOM from "react-dom/client";
import { AppProps, CustomProps, LifeCycleFn } from "single-spa";
```

I can open a PR if that's right

**Comment by filoxo** [comment]
I dove into it this weekend and found we hadn't known about `hydrateRoot` until the final React 18 release so I'll be looking to support that and and tests. That should really only affect users of TypeScript any anyone using hydrateRoot which is very likely no one at this time. 

I think I also learned that this change could be farther reaching if simply swapping out that import like I had initially done. That would mean a breaking change for this helper library which can actually be avoided as, syntactically, all of this code should still be able to work for prior versions of React too. Hopefully that's helpful information.

**Comment by JeffWeim** [comment]
@filoxo Thanks for looking into this further. I think this issue can be closed for now since everything is working. Let me know if there's anything to help out with with the updates

**Comment by filoxo** [comment]
Thank you, much appreciated! And thanks also to everyone else for your input too! 

I'd rather keep this ticket open and use it to communicate further updates. I've got a WIP branch I've yet to push up, as tests are what are taking a bit longer to figure out (and validate that both versions of React can be supported). However, I don't want to come across as "I'm the only one qualified to do this" so this is an open call if anyone would like to contribute/collaborate with me on this one. We can use this issue for that too.

**Comment by cdvillard** [comment]
So in bringing in single-spa-react v5.0.0 and using the alternative ReactDOM import you suggested works for me and removes the error, but after reading through this a bit, I'm still a little lost. Is this supposed to be the fix or is there further work to be done? I ask because, afaik, most React devs will reflexively reach for the former style of import.

**Comment by filoxo** [comment]
I still haven't merged in the documentation changes because I'm at home recovering from covid, but could you review them and see if they answer your question? https://github.com/single-spa/single-spa.js.org/pull/549 that'd really help me validate.

**Comment by filoxo** [comment]
I also failed to update this issue so [single-spa-react@5.0.0 release notes here](https://github.com/single-spa/single-spa-react/releases/tag/v5.0.0).
