### ISSUE TITLE
bug: multi parcel unmount error

### ISSUE THREAD

**Issue by CurtisHughes** [single-spa/single-spa-react#145]
**Describe the bug or question**
When rendering the same parcel multiple times within an application and then unmounting them at the same time (via navigation), single-spa will throw a timeout error that the parcel unmount function did not resolve or reject.

**To Reproduce**
Example repository to reproduce issue (using react-router-dom/navigateToUrl): https://github.com/CurtisHughes/multi-parcel-unmount-issue

**Expected behavior**
Both parcels should unmount individually and resolve.

**Screenshots and/or console output**
Error page: https://single-spa.js.org/error/?code=31&arg=unmount&arg=parcel&arg=parcel-0&arg=3000

https://user-images.githubusercontent.com/29492869/176707668-c01b204c-45cd-4557-a2db-98ca01fc58d4.mov

**Additional context**
I tried overriding the parcel's unmount function to check for the status of the parcel before attempting the base unmount. However, [getAppStatus](https://single-spa.js.org/docs/api/#getappstatus) doesn't seem to support parcels so I wasn't sure how to accomplish that. I also tried custom names for the parcel to see if that would distinguish them enough, but it didn't seem to matter.

**Comment by pbowden91** [comment]
Should be resolved by https://github.com/single-spa/single-spa-react/pull/161

**Comment by MilanKovacic** [comment]
Fixed in single-spa-react 5.1.0.
