### ISSUE TITLE
React 18 hydrateRoot support

### ISSUE THREAD

**Issue by mike-dvorscak-enablon** [single-spa/single-spa-react#149]
After upgrading to React 18, we're seeing a react console error:
![image](https://user-images.githubusercontent.com/57106451/183442410-696daa52-e056-471a-9329-330899c46287.png)

(error text: "ReactDOM.hydrate is no longer supported in React 18. Use hydrateRoot instead. Until you switch to the new API, your app will behave as if it's running React 17.")

When calling singleSpaReact with renderType = hydrate:
```ts
import React from "react";
import ReactDOM from "react-dom";
import singleSpaReact from "single-spa-react";
/* truncated for brevity */
singleSpaReact({
    React,
    ReactDOM,
    rootComponent,
    domElementGetter,
    renderType: "hydrate"
});
```

Will hydrateRoot be supported in PR https://github.com/single-spa/single-spa-react/pull/148? Do you know when that PR will be merged? 

P.S. the need for our project is not urgent, just curious to know the timeline for planning purposes.

**Comment by filoxo** [comment]
> Will hydrateRoot be supported in PR https://github.com/single-spa/single-spa-react/pull/148? 

Yes. You can verify this in the PR code here: https://github.com/single-spa/single-spa-react/pull/148/files#diff-cb30a967d456081f97d512503f30d39a71d3d112c66264972c01fbf8b7960ddaR15

> Do you know when that PR will be merged?

No ETA. I just want as many eyes on it from the core team, and our time has been limited lately.
