### ISSUE TITLE
Console Error - createRoot from react-dom

### ISSUE THREAD

**Issue by seanmcquaid** [single-spa/single-spa-react#151]
When implementing the newest version of single-spa-react, I noticed the following console error coming back : 

react-dom.development.js:86 Warning: You are importing createRoot from "react-dom" which is not supported. You should instead import it from "react-dom/client".

Reproduction Steps : 
1) Upgrade your single-spa-react, react, react-dom depedencies
2) Load your app
3) Notice the console error coming back

**Comment by brian-ziegler** [comment]
+1 to this, running into the same issue

**Comment by filoxo** [comment]
I took a look but haven't been able to replicate how to get this error on my end. I followed these steps:

- in application: upgrade single-spa-react, react, react-dom `npm i single-spa-react@latest react@latest react-dom@latest`
- in root config: upgrade shared dependency for react and react-dom in import map from `17.0.2` to `18.2.0`

At this point, I started it up expecting errors, but the application still rendered. So then I also updated the import to `import * as ReactDOM from 'react-dom/client';`and still the same.

However, the [renderType was set to `"createRoot"` by default](https://github.com/single-spa/single-spa-react/blob/c2cf48547226484d2e30ca74b90393ae6c998b01/src/single-spa-react.js#L39) in this latest release so its got to be related to that. Can you share a reproduction example of an application that shows this error when mounted? In the meantime, a full stacktrace might also be more telling of where the error is originating from.

**Comment by Jtango18** [comment]
Change your import to `import ReactDOMClient from "react-dom/client";` and then pass `ReactDOMClient` into your app instead.

**Comment by MilanKovacic** [comment]
Please follow instructions at https://single-spa.js.org/docs/ecosystem-react/#quickstart.
```javascript

import React from 'react';
import ReactDOMClient from 'react-dom/client';
import rootComponent from './path-to-root-component.js';
// SingleSpaContext is a react@16.3 (if available) context that provides singleSpa props
import singleSpaReact, { SingleSpaContext } from 'single-spa-react';

export const { bootstrap, mount, unmount } = singleSpaReact({
  React,
  ReactDOMClient,
  rootComponent,
  errorBoundary(err, info, props) {
    // https://reactjs.org/docs/error-boundaries.html
    return <div>This renders when a catastrophic error occurs</div>;
  },
});
```
