### ISSUE TITLE
Running react 18 and 17 on the same page without cross micro frontend imports

### ISSUE THREAD

**Issue by kbrah** [single-spa/single-spa-react#155]
I'm trying to create a new module in my existing micro frontend project with react 18. The rest of the modules are using 17. I'm getting an error application '@org/app' died in status SKIP_BECAUSE_BROKEN: Cannot create property '_updatedFibers' on number '0'. In my new module I am using externals that point to react 18 which I have in my importmap.
```
        externals: {
            react: "react-18",
            "react-dom": "react-dom-18",
        },

```

If I don't use react 18 as an external it seems to work fine. As far as I understood, multiple react versions should not cause issues as long as I don't have cross mf imports. Is there something I could do to fix this issue? It would be unfortunate if I had to upgrade all my modules to use react 18 at once.

**Comment by armedi** [comment]
I got the same issue here

**Comment by fealexandre** [comment]
I got the same issue here.

**Comment by MilanKovacic** [comment]
You could try running everything in React 17 compatibility mode until you upgrade all microfrontends:

https://react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-client-rendering-apis

**Comment by gjhommersom** [comment]
I ran into the same issue and shared my findings here: https://github.com/single-spa/single-spa-react/issues/175#issuecomment-1661532201.

In short: update the import map to React 18 and then update each microfrontend to React 18 as you please. Microfrontends that are not updated will behave as running under React 17,

**Comment by Tiberriver256** [comment]
If the solution provided by @gjhommersom doesn't work out and you do need to run React 17 **and** React 18 side by side. You'll want to re-bundle `react-dom` as a utility module with the externals re-pointing `react` to the correct version you want to use.

I wrote up a [detailed walkthrough](https://tiberriver256.github.io/web%20development/how-to-run-multiple-react-versions-using-single-spa/) and made a [repo for reference](https://github.com/Tiberriver256/multiple-react-versions-single-spa).

**Comment by MilanKovacic** [comment]
React 18 will run in compatibility mode until render is updated. This is the recommended upgrade path.
