### ISSUE TITLE
Local CORS

### ISSUE THREAD

**Issue by Fredleig** [single-spa/single-spa-react#159]
1) yarn create single-spa
2) yarn start --port 8500
3) Go to   http://single-spa-playground.org/playground/instant-test?name=@spa/spaReact&url=8500
![image](https://user-images.githubusercontent.com/44133252/210490814-42fd1142-4ef2-41dd-b54d-cec5c04bd400.png)

**Comment by MilanKovacic** [comment]
You need to configure CORS policy of the webpack development server. Please see https://stackoverflow.com/questions/31602697/webpack-dev-server-cors-issue.
