### ISSUE TITLE
package.json exports when using moduleResolution node16

### ISSUE THREAD

**Issue by webdeveric** [single-spa/single-spa-react#170]
When using `moduleResolution: "node16"` in `tsconfig.json`, the current `package.json` `exports` are not enough and TypeScript complains with:
> Could not find a declaration file for module 'single-spa-react'. '.../node_modules/single-spa-react/lib/esm/single-spa-react.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/single-spa-react` if it exists or add a new declaration (.d.ts) file containing `declare module 'single-spa-react';`

I manually edited your `package.json` in the `node_modules` folder and this config makes the error go away.

```json
{
  "exports": {
    ".": {
      "import": {
        "types": "./types/single-spa-react.d.ts",
        "default": "./lib/esm/single-spa-react.js"
      },
      "require": {
        "types": "./types/single-spa-react.d.ts",
        "default":"./lib/cjs/single-spa-react.cjs"
      }
    },
    "./parcel": {
      "import": {
        "types": "./types/single-spa-react.d.ts",
        "default": "./lib/esm/parcel.js"
      },
      "require": {
        "types": "./types/single-spa-react.d.ts",
        "default":"./lib/cjs/parcel.cjs"
      }
    },
    "./package.json": "./package.json"
  }
}
```

**Comment by awx-josh-fu** [comment]
Hi, what's the progress?
I see there was a PR raised, but for what reason it's not yet merged?

**Comment by MilanKovacic** [comment]
Hi, thank you for reporting the issue. 
We are waiting for additional changes before merging the PR.

**Comment by MilanKovacic** [comment]
I have opened a pull request #197 that will solve the problems. Feel free to help with testing it.
