### ISSUE TITLE
Options that correct for 5.0.2 are incorrect fo 5.1.1

### ISSUE THREAD

**Issue by ryufitreet** [single-spa/single-spa-react#177]
This is my module definition code. It works perfectly with 5.0.2:
```
import React from 'react'
import ReactDOMClient from 'react-dom/client'
import singleSpaReact from 'single-spa-react'

import App from './App'

const lifecycles = singleSpaReact({
  React,
  ReactDOMClient,
  rootComponent: App,
  errorBoundary(err, info, props): any {
    // Customize the root error boundary for your microfrontend here.
    return null
  },
})

export const { bootstrap, mount, unmount } = lifecycles
```
After update to 5.1.1 i got this error:
`application 'my-module' died in status LOADING_SOURCE_CODE: single-spa-react must be passed opts.ReactDOM`

React versions:
"react": "^18.2.0",
"react-dom": "^18.2.0",

**Comment by soumyart** [comment]
Getting the same here after updating to v5.1.1

**Comment by ibacher** [comment]
A little more context:

If I clone this repo and build it with `pnpm build`, the output files seem to be what I'd expect. However, in the version published as v5.1.1 on the npmjs.com registry, every version of single-spa-react.js has:

```js
if(!o.ReactDOM)throw new Error("single-spa-react must be passed opts.ReactDOM")
```

Where we'd expect:

```js
if(!o.ReactDOM&&!o.ReactDOMClient)throw new Error("single-spa-react must be passed opts.ReactDOM or opts.ReactDOMClient");
```

And the above is exactly what we do get when building from source.

If there is anything I can do to help resolve this, I'm happy to work on it, but it looks like this release might just need to be republished?

**Comment by islanddove** [comment]
@joeldenning

**Comment by ambroselittle** [comment]
This goes all the way back to 5.1. Just FYI.

**Comment by robmosca** [comment]
Indeed, it seems that the copy that is shipped with the NPM package of version 5.1.1 is coming from version 4.6.1.

**Comment by ndrwbv-dodo** [comment]
Same problem

**Comment by joeldenning** [comment]
This hopefully is fixed in https://github.com/single-spa/single-spa-react/releases/tag/v5.1.2
