### ISSUE TITLE
Discrepancy in the types config in package.json

### ISSUE THREAD

**Issue by colincclark** [single-spa/single-spa-react#207]
There is a minor discrepancy in the given configuration: the `"types"` field at the root level of the `package.json` incorrectly references a `.cts` file. Since `.cts` files are specific to TypeScript's support for CommonJS modules with the Node.js ECMAScript modules (ESM) syntax, they are not recognized by TypeScript for type definitions directly. TypeScript expects type definitions to be in `.d.ts` files. This is causing TS errors when importing:

> import singleSpaReact from "single-spa-react";

results in:

```
Could not find a declaration file for module 'single-spa-react'. '<my_path>/node_modules/single-spa-react/lib/umd/single-spa-react.js' implicitly has an 'any' type.
  ```
  
This is in the latest version `6.0.1`.

I have tried to set TS to consume the `.cts` file. The following is my TS config:

```
{
  "extends": "ts-config-single-spa",
  "compilerOptions": {
    "allowJs": true,
    "emitDeclarationOnly": false,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "lib": ["dom", "dom.iterable", "esnext"],
    "module": "CommonJS",
    "noEmit": true,
    "skipLibCheck": true,
    "strict": true,
    "target": "esnext",
    "useUnknownInCatchVariables": false
  },
  "files": ["react-app-env.d.ts"],
  "include": ["../../../src/**/*.ts", "../../../src/**/*.tsx"],
  "exclude": [
    "../../../i18next-parser.config.ts",
    "../../../build",
    "../../../node_modules",
    "../../../ui-library",
    "../../../src/__tests__/**",
    "../../../src/mocks/**"
  ]
}
```

No dice. Can you consider changing the `types` value in `package.json` or letting me know what I am doing wrong to keep getting these TS errors please?

**Comment by MilanKovacic** [comment]
I was not able to reproduce the issue. Can you please post a small reproduction repository?
".d.(c/mts)" type declaration files are common when providing multiple formats. They should be correctly parsed, even with node10 module resolution algorithm.

![image](https://github.com/single-spa/single-spa-react/assets/9189985/31bdac27-74dc-43a8-a352-e8c1e7f06c48)
![image](https://github.com/single-spa/single-spa-react/assets/9189985/8495fafb-c0d8-4460-b4dd-53c808a96f22)

**Comment by MilanKovacic** [comment]
Are you possibly using typescript < 4.7.0?
If you are, I recommend upgrading since that version is very old and does not support the cts/mts formats.
Due to the large amount of bundlers / resolution algorithms / typescript versions, it is not possible to verify all of the combinations.

**Comment by colincclark** [comment]
Yep, 4.2.9. I read on a blog post that `.cjs` support was introduced in 3.7, not 4.7, but having looked at the docs you are right. Closing this one, thanks.
