### ISSUE TITLE
Vite support?

### ISSUE THREAD

**Issue by franmc01** [single-spa/single-spa-react#209]
This plugin only works for CRA or can it be applied to vite react projects?

**Comment by webJose** [comment]
This plug-in is not dependant on the bundler you choose.  Works with webpack, vite, rollup and probably all other bundlers.  If you have an issue, you should describe it here, or in the Slack channel for single-spa.

**Comment by franmc01** [comment]
Yes, I want to set up a platform where I want to take advantage of Single SPA and take advantage of the advantages and "agility" of Vite, but in the doc I don't see something with its own support, like an own plugin as in Native Federation. I have nothing against webpack, I know that in these issues is the father of the chicks since he started with module federation.

**Comment by webJose** [comment]
I see, but you're asking in the wrong repository.  This repository is for a package that wraps a React component into a single-spa lifecycle object.  That's it.  Regardless of bundler, that's the job for this guy.  All you have to do is tell your bundler to consider whatever file you made that exports the single-spa lifecycle object an "input" file.  Then the bundler will works its magic and spit out bundled code whose origin is that file you created.  This is, as far as I can tell, how every bundler works.

Now, you might be asking if there are tools for Vite.  For that, visit the [Vite Ecosystem page](https://single-spa.js.org/docs/ecosystem-vite) in the docs.

I personally recommend you the use of `vite-plugin-single-spa`, which is a plug-in I created.  It is very opinionated, though, so be sure to read the documentation before you embark into using it.  If you decide to use it, though, it takes almost all complications of single-spa off your hands, including CSS mounting and unmounting.

**Comment by MilanKovacic** [comment]
As José replied, you can either use the Vite plugin, or a custom solution. Single-spa is bundler-agnostic.
