### ISSUE TITLE
Typescript support for Parcels?

### ISSUE THREAD

**Issue by zvertovsek** [single-spa/single-spa-react#44]
I can find some type definitions here https://www.npmjs.com/package/@types/single-spa-react but those doesn't include definitions for Parcels.

**Comment by Krzyrok** [comment]
old one but if somebody struggle with this, you can add file with typings to your repo:
single-spa-react.d.ts:
```
declare module 'single-spa-react/parcel' {
  import { Lifecycles } from 'single-spa-react';

  interface ParcelProps {
    // define here what props you need
    config: () => Promise<Lifecycles> | Lifecycles;
  }

  export default class Parcel extends React.Component<ParcelProps> {}
}
```

**Comment by joeldenning** [comment]
If anyone wants to add Parcels to the DefinitelyTyped types, that would be awesome.

**Comment by joeldenning** [comment]
This is resolved in single-spa-react@4
