### ISSUE TITLE
React Redux Connect is not working in SPA

### ISSUE THREAD

**Issue by KarthiZeus** [single-spa/single-spa-react#56]
I am trying to export the login page which is connected with redux. 
But it is not getting rendered in the page..
export default  connect(mapStateToProps, mapDispatchToProps)(LoginPage);

**Comment by joeldenning** [comment]
Hi @KarthiZeus, could you provide more detail?

Can you verify if your login single-spa application is in [MOUNTED](https://single-spa.js.org/docs/api.html#getappstatus) status? To do so, use the [single-spa-inspector](https://github.com/CanopyTax/single-spa-inspector) browser extension to see its status.

If the application is not in MOUNTED status, that is the problem. If it is in MOUNTED, please provide more detail for us to be able to diagnose.

**Comment by TheMcMurder** [comment]
Closed for inactivity
