### ISSUE TITLE
Possibility of passing callback function tu be run after render/hydrate

### ISSUE THREAD

**Issue by brunocanepa** [single-spa/single-spa-react#64]
`ReactDOM.render` and `ReactDOM.hydrate` receives an optional `callback` as third param, which is called after the render/hydrate has finished. There is a possibility to do that with this package? Because in the docs is not specified.
Link to React's doc: https://reactjs.org/docs/react-dom.html#hydrate & https://reactjs.org/docs/react-dom.html#render

Thanks!

**Comment by frehner** [comment]
Looks like we don't currently support it, but we actually use it ourselves:

https://github.com/single-spa/single-spa-react/blob/master/src/single-spa-react.js#L192

The `whenFinished` function is just a custom function defined by us

https://github.com/single-spa/single-spa-react/blob/master/src/single-spa-react.js#L91-L93

so I think it would just take passing in a new function and adding it to the body of `whenFinished` so it's called before `resolve(this)`. 

Would probably be a good candidate for a first PR :)

**Comment by joeldenning** [comment]
This is already possible and supported - no changes needed:

```js
const lifecycles = singleSpaReact({...})

export const mount = [
  lifecycles.mount,
  async () => {
    console.log('ReactDOM.render / ReactDOM/hydrate finished!')
  }
]
```

See more [in these docs](https://single-spa.js.org/docs/building-applications#registered-application-lifecycle) about setting lifecycle functions like `mount` to an array.
