### ISSUE TITLE
Parcel component in 'single-spa-react/parcel' vs 'single-spa-react'

### ISSUE THREAD

**Issue by nkimaina** [single-spa/single-spa-react#65]
single-spa-react exposes 2 parcel components i.e I can import the parcel component in two ways:
1. import Parcel from "single-spa-react/parcel";
2. import Parcel from "single-spa-react";

Using component 1) works while using 2) does not work. What's the difference?

**Comment by joeldenning** [comment]
You cannot do 2, only 1. We only export Parcel from the `single-spa-react/parcel` path
