### ISSUE TITLE
singleSpaReact’s domElementGetter function No arguments？

### ISSUE THREAD

**Issue by yuanman0109** [single-spa/single-spa-react#71]
If there's a scenario like this，child app need root app  pass a parameter to judge mount which one dom。example：
![image](https://user-images.githubusercontent.com/22994293/78358213-6030e880-75e5-11ea-970e-23a8c0ab57f3.png)

I hope to get the props，but ，Does not support now；Is there any other way？

**Comment by joeldenning** [comment]
Hi @yuanman0109 - right now single-spa-react does not pass the single-spa props to the dom element getter. The props are only passed to the lifecycle functions, not the dom element getter.

I'd be okay adding this feature to single-spa-react, though, and will put together a PR to add it. I will transfer this issue to single-spa-react.

**Comment by yuanman0109** [comment]
> This is now supported in https://github.com/single-spa/single-spa-react/releases/tag/v2.13.0

very very good, I didn't expect to be so efficient；The reason why need props is because my child component both as a pop-up box and as a router page, so I need it to judge；Thank you very much for supporting this feature；Do I need to upgrade the single-spa-react？

**Comment by joeldenning** [comment]
Yes you must upgrade to single spa react 2.13.0
