### ISSUE TITLE
Passing customProps to Micro application with Parcel breaks the mounting phase

### ISSUE THREAD

**Issue by pavlo-kerestey-zalando** [single-spa/single-spa-react#82]
**Describe the bug or question**
In the [lifecycle documentation](https://single-spa.js.org/docs/building-applications#lifecyle-props), the lifecycle props are said to certainly contain a customProps object, however, when we load an application as a Parcel, `customProps` field is undefined. In fact, setting `customProps` on `parcelProps` actually breaks the micro application.

It works when I don't pass customProps field though, and pass with another name instead like this:

```
singleSpa.mountRootParcel(component, {
   domElement: document.getElementById("element-id"),
   ourCustomProps: { foo: "bar" },
   });
```

So I am unsure what I am doing wrong there.

**To Reproduce**

pass `customProps` to parcel as

```
singleSpa.mountRootParcel(component, {
   domElement: document.getElementById("element-id"),
   customProps: { foo: "bar" },
   });
```

**Expected behavior**
The micro application is loaded, and `customProps = { foo: "bar" }` is present in the `props` in each of the lifecycles of the loaded application.

**Screenshots and/or console output**
`Error: parcel 'parcel-1' died in status SKIP_BECAUSE_BROKEN: single-spa-react was not given an application name as a prop, so it can't make a unique dom element container for the react application`

**Comment by joeldenning** [comment]
I have identified that this is a bug with single-spa-react, so I transferred this issue to single-spa-react.

**Comment by joeldenning** [comment]
Fix at https://github.com/single-spa/single-spa-react/pull/83

**Comment by joeldenning** [comment]
Fix released in https://github.com/single-spa/single-spa-react/releases/tag/v3.0.1
