### ISSUE TITLE
Error: single-spa-react must be passed opts.React 

### ISSUE THREAD

**Issue by Flamingo09** [single-spa/single-spa-react#85]
I'm including react and react-dom as external. And as soon as I remove them from external, or when i copy parcel and single-spa-react in my project, the error will disappear. 
Here is the stack trace:
```
Error: single-spa-react must be passed opts.React

    in Component (created by Context.Consumer)
    in ErrorBoundary (created by Context.Consumer)
    in Route (created by App)
    in Switch (created by App)
    in div (created by App)
    in App (created by HotExportedApp)
    in AppContainer (created by HotExportedApp)
    in HotExportedApp (created by Root)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Context.Consumer)
    in ConnectedRouterWithContext (created by ConnectFunction)
    in ConnectFunction (created by Root)
    in Provider (created by Root)
    in Root
    in AppContainer
    in ErrorBoundary
```

here is my project link  [root-config](https://github.com/Managing-Microfront-ends/root-config)

**Comment by Flamingo09** [comment]
changed external 
```
externals: [
   'react',
   'react-dom'
]
```

to externals: {
  'react': 'React',
  'react-dom': 'ReactDOM'
}

**Comment by joeldenning** [comment]
I tried cloning the repo locally and running `npm start`, but I get compilation errors before I can run it in the browser.

When using webpack externals, you must be aware of where the external is coming from. In your case, the webpack config's output format is umd2 ([link](https://github.com/Managing-Microfront-ends/root-config/blob/048712df9ef82ce11aa498d7fd79415afda9fa7f/webpack.config.dev.js#L29)) which means that the external could come from an AMD loader (such as SystemJS) or from a global variable `window.React`. You'll need to make sure that React/ReactDOM are available in SystemJS or as global variables in order for it to work.

**Comment by Flamingo09** [comment]
Closing this issue, as I found what I was doing wrong. Here in release tag Joel has specified the breaking changes : 
https://github.com/single-spa/single-spa-react/releases/tag/v3.0.0

**Comment by joeldenning** [comment]
I'm glad you got it working 👍
