### ISSUE TITLE
How to use "global" domElement/domElementGetter?

### ISSUE THREAD

**Issue by GasimGasimzada** [single-spa/single-spa-react#86]
**Describe the bug or question**

In the [documentation](https://single-spa.js.org/docs/ecosystem-react/#options), there is a note about using `domElementGetter`:

> domElementGetter: (optional) A function that is given the single-spa props and returns a DOMElement. This dom element is where the React application will be bootstrapped, mounted, and unmounted. Note that this opt can be omitted. When omitted, the domElementGetter or domElementcustom single-spa props are used. To use those, do `singleSpa.registerApplication({ name, app, activeWhen, customProps: {domElementGetter: function() {...}} })` or `singleSpa.registerApplication({ name, app, activeWhen, {domElement: document.getElementById(...)} })`. If no dom element can be found through any of those methods, then a container div will be created and appended to document.body, by default.

However, I am not able to get this running:

```
registerApplication({
  name: app.appName,
  app: app.loadFn,
  activeWhen: app.activeFn,
  customProps: {
    customProps,
    domElementGetter: () => {
      console.log('dom element getter');
      return document.getElementById(app.appName) // the DOM element exists in the document
    }
  }
});
```

It keeps throwing error that it cannot find the dom element for a specific app:

> SKIP_BECAUSE_BROKEN: Cannot mount react application 'my-app' without a domElementGetter provided in either opts or props

**Comment by joeldenning** [comment]
Glad to hear that you got it working 👍
