### ISSUE TITLE
Props name not getting picked up

### ISSUE THREAD

**Issue by Flamingo09** [single-spa/single-spa-react#89]
I'm calling my Microapp using 
```javascript
<Parcel config={remoteImport(this.props.moduleName)}
                  mountParcel={mountRootParcel}
                  basename={this.props.basename}
                  name={this.props.appName}
                  history={this.props.history}
          />
```

According to the code, a domElement should be created with ID 
```javascript
const htmlId = `single-spa-application:${appName}`;
```

But when I print props in mount promise, the name comes as parcel-0 and one domElement is already present which is getting used as dom to render the micro app.

Hence when I call unmount on microApp, it gives me this error
```javascript
react-dom.development.js:25029 Uncaught (in promise) Error: unmountComponentAtNode(...): Target container is not a DOM element
```

Also , in this unmount promise, it looks for 
```javascript
opts.ReactDOM.unmountComponentAtNode(opts.domElements[props.name]);
```

Here, during unmount the props.name is correct, i.e. same as what I'm passing. Hence it throws error, coz it has created a dom using parcel-0. Also here shouldn't it look for 
```javascript
single-spa-application:${appName}
```
instead of just looking for props.name.

**Comment by Flamingo09** [comment]
Irrelevant. After going through the code, I have got some clarity.

**Comment by joeldenning** [comment]
Glad to hear you got things working.

**Comment by joeldenning** [comment]
For anyone else looking at this, here is a code sandbox that shows that the `name` prop is working properly: https://codesandbox.io/s/dazzling-jackson-lmudo?file=/index.html
