### ISSUE TITLE
application '@myapp/learn' died in status LOADING_SOURCE_CODE: Error loading http://localhost:8500/myapp-learn.js (SystemJS Error#3 https://git.io/JvFET#3)     at HTMLScriptElement.<anonymous>

### ISSUE THREAD

**Issue by shivarajsb** [single-spa/single-spa-react#97]
Getting the above error while trying to run my react application

**Comment by frehner** [comment]
The error itself has a link to a page where you can find help on how to solve it. 

For convenience, here is the link again https://github.com/systemjs/systemjs/blob/master/docs/errors.md#3
