### ISSUE TITLE
Uncaught ReferenceError: application '@learn/MyTestPlatform' died in status LOADING_SOURCE_CODE: regeneratorRuntime is not defined     at Module../src/services/TestSpecific.api.js (learn-MyTestPlatform.js:89889)     at __webpack_require__ (bootstrap:63)

### ISSUE THREAD

**Issue by shivarajsb** [single-spa/single-spa-react#98]
Hi I'm getting the following error while trying to run the application. Please can you tell me what I'll need to add or change?

**Comment by filoxo** [comment]
In your root-config, did you remove [this line](https://github.com/single-spa/create-single-spa/blob/master/packages/generator-single-spa/src/root-config/templates/src/index.ejs#L13)?

**Comment by frehner** [comment]
Closing as this isn’t a bug in single-spa. 

Feel free to continue to ask questions here, or also consider joining the slack org (there’s a link at the bottom of the website)
